# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_on_main',
            field=models.BooleanField(default=False),
        ),
    ]
